
package Vista;

import Controlador.CtrlPreguntas;
import Modelo.ModConexion;
import Modelo.ModConsultasSQL;
import Modelo.ModvariablesPreguntas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *  Esta es la interfaz de Preguntas (al haber seleccionado agregar preguntas de la 
 * interfaz Quizzes) en donde podemos agregar la pregunta, el tipo de pregunta,
 * cantidad de respuestas, puntuación para cada respuesta y sus respectivas modificaciones. 
 * @author Karina Carmona, Antonio Cetzal, Jessica González y Jesús Pacheco.
 * @version 02/12/2018/ProyectoPoo_Acompañamiento
 */

public class VstPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form VstPreguntas
     */
    public VstPreguntas() {
        initComponents();
//        SpinnerNumberModel ptt = new SpinnerNumberModel(000.00, 000.00, 100.00, 000.01);
//        spinnerPuntos.setModel(ptt);
        btnReestablecer.setVisible(false);
        btnEliminar.setVisible(false);
        btnModificar.setVisible(false);
        matricula.setVisible(false);
        idP.setVisible(false);
        id.setVisible(false);
        actual.setVisible(false);
        modPre.setVisible(false);
        pregunt.setVisible(false);

        CtrlPreguntas.inicio(r2, r3, r4, false, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
        t = new Timer(10, acciones);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtR4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreguntas = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtR1 = new javax.swing.JTextField();
        txtR2 = new javax.swing.JTextField();
        txtR3 = new javax.swing.JTextField();
        txtD3 = new javax.swing.JTextField();
        txtD2 = new javax.swing.JTextField();
        txtD1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnReestablecer = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        r4 = new javax.swing.JCheckBox();
        unico = new javax.swing.JCheckBox();
        multiple = new javax.swing.JCheckBox();
        r2 = new javax.swing.JCheckBox();
        r3 = new javax.swing.JCheckBox();
        abierto = new javax.swing.JCheckBox();
        id = new javax.swing.JTextField();
        actual = new javax.swing.JTextField();
        R4 = new javax.swing.JTextField();
        R1 = new javax.swing.JTextField();
        R2 = new javax.swing.JTextField();
        R3 = new javax.swing.JTextField();
        txtD4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPreguntas = new javax.swing.JTable();
        idP = new javax.swing.JTextField();
        matricula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        modPre = new javax.swing.JCheckBox();
        pregunt = new javax.swing.JTextField();
        puntos = new javax.swing.JTextField();
        p_totales = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Quizz:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 680, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("<html>Puntuacion de esta pregunta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pregunta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Respuestas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtR4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 300, -1));

        jScrollPane1.setViewportView(txtPreguntas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 680, 60));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 50, 200));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 850, 20));

        txtR1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 300, -1));

        txtR2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 300, -1));

        txtR3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 300, -1));

        txtD3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 300, -1));

        txtD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 300, -1));

        txtD1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Distractores:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("<html>Cantidad de Respuestas:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Puntos:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        btnGuardar.setText("Guardar");
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, -1, -1));

        btnReestablecer.setText("Reestablecer");
        jPanel1.add(btnReestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        buttonGroup2.add(r4);
        r4.setText("4");
        r4.setContentAreaFilled(false);
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        jPanel1.add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        buttonGroup1.add(unico);
        unico.setText("Única");
        unico.setContentAreaFilled(false);
        unico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unicoActionPerformed(evt);
            }
        });
        jPanel1.add(unico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        buttonGroup1.add(multiple);
        multiple.setText("Múltiple");
        multiple.setContentAreaFilled(false);
        multiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleActionPerformed(evt);
            }
        });
        jPanel1.add(multiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        buttonGroup2.add(r2);
        r2.setText("2");
        r2.setContentAreaFilled(false);
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        buttonGroup2.add(r3);
        r3.setText("3");
        r3.setContentAreaFilled(false);
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        buttonGroup1.add(abierto);
        abierto.setText("Abierto");
        abierto.setContentAreaFilled(false);
        abierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abiertoActionPerformed(evt);
            }
        });
        jPanel1.add(abierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setBorder(null);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, -1));

        actual.setEditable(false);
        actual.setBackground(new java.awt.Color(255, 255, 255));
        actual.setBorder(null);
        jPanel1.add(actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 90, -1));
        jPanel1.add(R4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 120, -1));
        jPanel1.add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 120, -1));
        jPanel1.add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 120, -1));
        jPanel1.add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 120, -1));

        txtD4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 300, -1));

        tablaPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Pregunta", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPreguntasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPreguntas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 430, 160));

        idP.setEditable(false);
        idP.setBackground(new java.awt.Color(255, 255, 255));
        idP.setBorder(null);
        jPanel1.add(idP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 90, -1));

        matricula.setEditable(false);
        matricula.setBackground(new java.awt.Color(255, 255, 255));
        matricula.setBorder(null);
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Preguntas restantes: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        modPre.setText("Modificar pregunta");
        modPre.setContentAreaFilled(false);
        modPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modPreActionPerformed(evt);
            }
        });
        jPanel1.add(modPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pregunt.setEditable(false);
        pregunt.setBackground(new java.awt.Color(255, 255, 255));
        pregunt.setBorder(null);
        jPanel1.add(pregunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 50, -1));
        jPanel1.add(puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, -1));

        p_totales.setEditable(false);
        p_totales.setBackground(new java.awt.Color(255, 255, 255));
        p_totales.setBorder(null);
        jPanel1.add(p_totales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tipo de respuesta:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unicoActionPerformed
        CtrlPreguntas.unico(unico, r2, r3, r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
    }//GEN-LAST:event_unicoActionPerformed

    private void multipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleActionPerformed
        CtrlPreguntas.multiple(multiple, r2, r3, r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
    }//GEN-LAST:event_multipleActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        CtrlPreguntas.r2(r2, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        CtrlPreguntas.r3(r3, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        CtrlPreguntas.r4(r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
    }//GEN-LAST:event_r4ActionPerformed

    private void abiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abiertoActionPerformed
        if (abierto.isSelected() == true) {
            CtrlPreguntas.inicio(r2, r3, r4, false, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
        }
    }//GEN-LAST:event_abiertoActionPerformed

    ModvariablesPreguntas var = new ModvariablesPreguntas();

    private void tablaPreguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPreguntasMouseClicked
        int row = evt.getY() / tablaPreguntas.getRowHeight();
        //String id = "" + tablaPreguntas.getValueAt(row, 0);
        idP.setText("" + tablaPreguntas.getValueAt(row, 0));

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;

            ModConexion objCon = new ModConexion();
            Connection con = objCon.getConexion();

            int Fila = tablaPreguntas.getSelectedRow();
            String codigo = tablaPreguntas.getValueAt(Fila, 0).toString();

            ps = con.prepareStatement("SELECT * FROM preguntas WHERE id = ?");
            ps.setString(1, codigo);
            rs = ps.executeQuery();

            while (rs.next()) {
                if (rs.getString(4).equals("abierto")) {
                    CtrlPreguntas.inicio(r2, r3, r4, false, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
                    abierto.setSelected(true);
                    idP.setText(rs.getString(1));
                    id.setText(rs.getString(2));
                    txtPreguntas.setText(rs.getString(3));
                    pregunt.setText(rs.getString(3));
                    puntos.setText(rs.getString(6));

                } else if (rs.getString(4).equals("unico")) {
                    CtrlPreguntas.unico(unico, r2, r3, r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
                    unico.setSelected(true);
                    idP.setText(rs.getString(1));
                    id.setText(rs.getString(2));
                    txtPreguntas.setText(rs.getString(3));
                    pregunt.setText(rs.getString(3));
                    puntos.setText(rs.getString(6));

                    txtR1.setText(rs.getString(7));
                    txtD1.setText(rs.getString(15));
                    
                    if (rs.getString(16).equals("*/null/*")); else {
                        txtD2.setText(rs.getString(16));
                    }
                    if (rs.getString(17).equals("*/null/*")); else {
                        txtD3.setText(rs.getString(17));
                    }
                    if (rs.getString(18).equals("*/null/*")); else {
                        txtD4.setText(rs.getString(18));
                    }

                } else if (rs.getString(4).equals("multiple")) {
                    CtrlPreguntas.multiple(multiple, r2, r3, r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
                    multiple.setSelected(true);
                    idP.setText(rs.getString(1));
                    id.setText(rs.getString(2));
                    txtPreguntas.setText(rs.getString(3));
                    pregunt.setText(rs.getString(3));
                    puntos.setText(rs.getString(6));

                    if (rs.getString(5).equals("2")) {
                        CtrlPreguntas.r2(r2, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
                        r2.setSelected(true);

                        txtR1.setText(rs.getString(7));
                        R1.setText(rs.getString(8));
                        txtR2.setText(rs.getString(9));
                        R2.setText(rs.getString(10));

                        if (rs.getString(15).equals("*/null/*")); else {
                            txtD1.setText(rs.getString(15));
                        }
                        if (rs.getString(16).equals("*/null/*")); else {
                            txtD2.setText(rs.getString(16));
                        }

                    } else if (rs.getString(5).equals("3")) {
                        CtrlPreguntas.r3(r3, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
                        r3.setSelected(true);

                        txtR1.setText(rs.getString(7));
                        R1.setText(rs.getString(8));
                        txtR2.setText(rs.getString(9));
                        R2.setText(rs.getString(10));
                        txtR3.setText(rs.getString(11));
                        R3.setText(rs.getString(12));

                        if (rs.getString(15).equals("*/null/*")); else {
                            txtD1.setText(rs.getString(15));
                        }
                        if (rs.getString(16).equals("*/null/*")); else {
                            txtD2.setText(rs.getString(16));
                        }
                        if (rs.getString(17).equals("*/null/*")); else {
                            txtD3.setText(rs.getString(17));
                        }

                    } else if (rs.getString(5).equals("4")) {
                        CtrlPreguntas.r4(r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, txtD4);
                        r4.setSelected(true);

                        txtR1.setText(rs.getString(7));
                        R1.setText(rs.getString(8));
                        txtR2.setText(rs.getString(9));
                        R2.setText(rs.getString(10));
                        txtR3.setText(rs.getString(11));
                        R3.setText(rs.getString(12));
                        txtR4.setText(rs.getString(13));
                        R4.setText(rs.getString(14));

                        if (rs.getString(15).equals("*/null/*")); else {
                            txtD1.setText(rs.getString(15));
                        }
                        if (rs.getString(16).equals("*/null/*")); else {
                            txtD2.setText(rs.getString(16));
                        }
                        if (rs.getString(17).equals("*/null/*")); else {
                            txtD3.setText(rs.getString(17));
                        }
                        if (rs.getString(18).equals("*/null/*")); else {
                            txtD4.setText(rs.getString(18));
                        }

                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(VstPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        }

        btnReestablecer.setVisible(true);
        btnEliminar.setVisible(true);
        btnModificar.setVisible(true);
        btnGuardar.setVisible(false);
        modPre.setVisible(true);
        txtPreguntas.setEditable(false);
    }//GEN-LAST:event_tablaPreguntasMouseClicked

    private void modPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modPreActionPerformed
        if (modPre.isSelected() == true) {
            txtPreguntas.setEditable(true);
        } else {
            txtPreguntas.setEditable(false);
        }
    }//GEN-LAST:event_modPreActionPerformed

    /**
     * @param args the command line arguments
     */
    private Timer t;
    private int h, m, s, cs;

    /**
    * Método para el cronómetro.
    * @param ae encargada de recibir cada accion de los botones de la interfaz.
    */ 

    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            cs++;
            if (cs == 100) {
                cs = 0;
                ++s;
            }
            if (cs == 0 && (s % 5 == 0)) {
                ModvariablesPreguntas var = new ModvariablesPreguntas();
                ModConsultasSQL.tablaPreg(tablaPreguntas, var, id.getText());
            }
            if (s == 60) {
                s = 0;
                ++m;
            }
            if (m == 60) {
                m = 0;
                ++h;
            }
//            actualizarLabel();
        }
    };

//    private void actualizarLabel() {
//        String tiempo = (h <= 9 ? "0" : "") + h + ":" + (m <= 9 ? "0" : "") + m + ":" + (s <= 9 ? "0" : "") + s + ":" + (cs <= 9 ? "0" : "") + cs;
//        cronometro.setText(tiempo);
//    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField R1;
    public javax.swing.JTextField R2;
    public javax.swing.JTextField R3;
    public javax.swing.JTextField R4;
    public javax.swing.JCheckBox abierto;
    public javax.swing.JTextField actual;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnReestablecer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JTextField id;
    public javax.swing.JTextField idP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField matricula;
    public javax.swing.JCheckBox modPre;
    public javax.swing.JCheckBox multiple;
    public javax.swing.JTextField p_totales;
    public javax.swing.JTextField pregunt;
    public javax.swing.JTextField puntos;
    public javax.swing.JCheckBox r2;
    public javax.swing.JCheckBox r3;
    public javax.swing.JCheckBox r4;
    public javax.swing.JTable tablaPreguntas;
    public javax.swing.JTextField txtD1;
    public javax.swing.JTextField txtD2;
    public javax.swing.JTextField txtD3;
    public javax.swing.JTextField txtD4;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextPane txtPreguntas;
    public javax.swing.JTextField txtR1;
    public javax.swing.JTextField txtR2;
    public javax.swing.JTextField txtR3;
    public javax.swing.JTextField txtR4;
    public javax.swing.JCheckBox unico;
    // End of variables declaration//GEN-END:variables
}
