/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ModConsultasSQL;
import Modelo.ModVariablesQuizzes;
import Modelo.ModVariablesUsr;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 * Es la interfaz para que el empleado seleccione el quiz a realizar. 
 * @author Karina Carmona, Antonio Cetzal, Jessica González y Jesús Pacheco.
 * @version 02/12/2018/ProyectoPoo_Acompañamiento
 */
public class VstSelectQuizz extends javax.swing.JFrame {

    /**
     * Creates new form VstSelectQuizz
     */
    public VstSelectQuizz() {
        initComponents();
        Quizz.setVisible(false);
        matricula.setVisible(false);
        
        t = new Timer(10, acciones);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSelectQuizz = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Quizz = new javax.swing.JTextField();
        btnPresentar = new javax.swing.JButton();
        matricula = new javax.swing.JTextField();
        txtAviso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaSelectQuizz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre:", "Preguntas:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSelectQuizz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSelectQuizzMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSelectQuizz);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Selecione el Quizz que desea presentar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Quizz.setEditable(false);
        Quizz.setBackground(new java.awt.Color(255, 255, 255));
        Quizz.setBorder(null);
        jPanel1.add(Quizz, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, -1));

        btnPresentar.setText("Presentar Quizz");
        btnPresentar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnPresentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 140, -1));

        matricula.setEditable(false);
        matricula.setBackground(new java.awt.Color(255, 255, 255));
        matricula.setBorder(null);
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 100, -1));

        txtAviso.setEditable(false);
        txtAviso.setBackground(new java.awt.Color(255, 255, 255));
        txtAviso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAviso.setText("Sin seleccionar Quizz.");
        txtAviso.setBorder(null);
        jPanel1.add(txtAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, 260, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaSelectQuizzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSelectQuizzMouseClicked
        int row = evt.getY() / tablaSelectQuizz.getRowHeight();
        String quizz = "" + tablaSelectQuizz.getValueAt(row, 0);
        String nump = "" + tablaSelectQuizz.getValueAt(row, 1);
        String tiempo = "" + tablaSelectQuizz.getValueAt(row, 2);
        
        this.Quizz.setText(quizz + "/" + nump + "/" + tiempo);
        txtAviso.setText("Quiz seleccionado: " + quizz);
    }//GEN-LAST:event_tablaSelectQuizzMouseClicked

    /**
     * @param args the command line arguments
     */
    
    private Timer t;
    private int h, m, s, cs;
    private ActionListener acciones = new ActionListener() {
        @Override

        /**
        * @param ae encargada de recibir cada accion de los botones de la interfaz.
        */ 

        public void actionPerformed(ActionEvent ae) {
            ModVariablesUsr var = new ModVariablesUsr();
            Date date = new Date();
            DateFormat horaDate = new SimpleDateFormat("HH:mm:ss");
            DateFormat fechaDate = new SimpleDateFormat("dd/MM/yyyy");

            var.setMatricula(matricula.getText());
            var.setDia(fechaDate.format(date));
            var.setHora(horaDate.format(date));

            cs++;
            if (cs == 100) {
                cs = 0;
                ++s;
            }
            if (cs == 0 && (s % 2 == 0)) {
                ModVariablesQuizzes varQ = new ModVariablesQuizzes();
                ModConsultasSQL.tablaSelectQuiz(tablaSelectQuizz, varQ);
            }
            if (s == 60) {
                s = 0;
                ++m;
            }
            if (m == 60) {
                m = 0;
                ++h;
            }

        }
    };
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstSelectQuizz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstSelectQuizz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstSelectQuizz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstSelectQuizz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstSelectQuizz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Quizz;
    public javax.swing.JButton btnPresentar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField matricula;
    public javax.swing.JTable tablaSelectQuizz;
    public javax.swing.JTextField txtAviso;
    // End of variables declaration//GEN-END:variables
}
