/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Mensajes;

import Controlador.CtrlMensajes.CtrlRecibido;
import Modelo.ModConsultasSQL;
import Modelo.ModVariablesMensaje;
import Modelo.ModVariablesUsr;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Antonio
 */
public class VstBandejadEntrada extends javax.swing.JFrame {

    /**
     * Creates new form VstBandejadEntrada
     */
    public VstBandejadEntrada() {
        initComponents();
        matricula.setVisible(false);
        t = new Timer(10, acciones);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBandejaEntrada = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTUsuarios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEnviados = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 50, 600));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tablaBandejaEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID:", "De:", "Asunto:", "Fecha:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaBandejaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBandejaEntradaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBandejaEntrada);
        if (tablaBandejaEntrada.getColumnModel().getColumnCount() > 0) {
            tablaBandejaEntrada.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablaBandejaEntrada.getColumnModel().getColumn(2).setPreferredWidth(290);
            tablaBandejaEntrada.getColumnModel().getColumn(3).setPreferredWidth(110);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 630, 540));

        tablaTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Usuarios:", "Tipo:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaTUsuarios);
        if (tablaTUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaTUsuarios.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 430));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo mensaje");
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        btnEnviados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEnviados.setText("Mensajes enviados");
        jPanel1.add(btnEnviados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 220, -1));

        txtMatricula.setEditable(false);
        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mensajes:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        matricula.setEditable(false);
        matricula.setBackground(new java.awt.Color(255, 255, 255));
        matricula.setBorder(null);
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTUsuariosMouseClicked
        int row = evt.getY() / tablaTUsuarios.getRowHeight();
        btnNuevo.setVisible(true);

        String ident = "" + tablaTUsuarios.getValueAt(row, 0);
        String[] part = ident.split("/");
        String part1 = part[0];
        String part2 = part[1];

        txtMatricula.setText(part1);
        txtNombre.setText(part2);

    }//GEN-LAST:event_tablaTUsuariosMouseClicked

    private void tablaBandejaEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBandejaEntradaMouseClicked
        int row = evt.getY() / tablaBandejaEntrada.getRowHeight();
        String id = "" + tablaBandejaEntrada.getValueAt(row, 0);
        String status = "" + tablaBandejaEntrada.getValueAt(row, 4);
        String ident = "" + tablaBandejaEntrada.getValueAt(row, 1);

        VstRecibido vr = new VstRecibido();
        ModConsultasSQL con = new ModConsultasSQL();
        ModVariablesMensaje var = new ModVariablesMensaje();
        ModVariablesUsr varU = new ModVariablesUsr();
        ModConsultasSQL.recibidos(tablaBandejaEntrada, var, varU);
        varU.setMatricula(matricula.getText());
        ModVariablesMensaje varM = new ModVariablesMensaje();
        CtrlRecibido ctrlR = new CtrlRecibido(con, varU, varM, vr, this);
        ctrlR.iniciar();
        ModConsultasSQL.leer(id, status, vr, var);
        vr.ident.setText(ident);
        ModConsultasSQL.recibidos(tablaBandejaEntrada, var, varU);
    }//GEN-LAST:event_tablaBandejaEntradaMouseClicked

    /**
     * @param args the command line arguments
     */
    private Timer t;
    private int h, m, s, cs;

    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            cs++;
            if (cs == 100) {
                cs = 0;
                ++s;
            }
            if (cs == 0 && (s % 5 == 0)) {
                ModVariablesMensaje varM = new ModVariablesMensaje();
                ModVariablesUsr var = new ModVariablesUsr();
                var.setMatricula(matricula.getText());
                ModConsultasSQL.recibidos(tablaBandejaEntrada, varM, var);
            }
            if (s == 60) {
                s = 0;
                ++m;
            }
            if (m == 60) {
                m = 0;
                ++h;
            }
//            actualizarLabel();
        }
    };

//    private void actualizarLabel() {
//        String tiempo = (h <= 9 ? "0" : "") + h + ":" + (m <= 9 ? "0" : "") + m + ":" + (s <= 9 ? "0" : "") + s + ":" + (cs <= 9 ? "0" : "") + cs;
//        cronometro.setText(tiempo);
//    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstBandejadEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstBandejadEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstBandejadEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstBandejadEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstBandejadEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEnviados;
    public javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField matricula;
    public javax.swing.JTable tablaBandejaEntrada;
    public javax.swing.JTable tablaTUsuarios;
    public javax.swing.JTextField txtMatricula;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
