/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Administrador;

import Controlador.Administrador.CtrlPreguntas;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class VstPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form VstPreguntas
     */
    public VstPreguntas() {
        initComponents();
//        SpinnerNumberModel ptt = new SpinnerNumberModel(000.00, 000.00, 100.00, 000.01);
//        spinnerPuntos.setModel(ptt);
        btnEliminar.setVisible(false);
        btnModificar.setVisible(false);

        CtrlPreguntas.inicio(r2, r3, r4, false, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, D1, D2, D3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtR4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreguntas = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtR1 = new javax.swing.JTextField();
        txtR2 = new javax.swing.JTextField();
        txtR3 = new javax.swing.JTextField();
        txtD3 = new javax.swing.JTextField();
        txtD2 = new javax.swing.JTextField();
        txtD1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        r4 = new javax.swing.JCheckBox();
        unico = new javax.swing.JCheckBox();
        multiple = new javax.swing.JCheckBox();
        r2 = new javax.swing.JCheckBox();
        r3 = new javax.swing.JCheckBox();
        abierto = new javax.swing.JCheckBox();
        id = new javax.swing.JTextField();
        actual = new javax.swing.JTextField();
        R4 = new javax.swing.JTextField();
        R1 = new javax.swing.JTextField();
        R2 = new javax.swing.JTextField();
        R3 = new javax.swing.JTextField();
        D1 = new javax.swing.JTextField();
        D2 = new javax.swing.JTextField();
        D3 = new javax.swing.JTextField();
        puntos = new javax.swing.JTextField();
        QPR = new javax.swing.JButton();
        QPD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Quizz:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 520, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("<html>Puntuacion de esta pregunta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pregunta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo de respuesta:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Respuestas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtR4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 160, -1));

        jScrollPane1.setViewportView(txtPreguntas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 520, 60));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 50, 200));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 700, 20));

        txtR1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 160, -1));

        txtR2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 160, -1));

        txtR3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 160, -1));

        txtD3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 160, -1));

        txtD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 160, -1));

        txtD1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Distractores:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("<html>Cantidad de Respuestas:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Puntos:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Puntos:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        btnGuardar.setText("Guardar");
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        btnTodos.setText("Todas las preguntas del Quizz");
        jPanel1.add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        buttonGroup2.add(r4);
        r4.setText("4");
        r4.setContentAreaFilled(false);
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        jPanel1.add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        buttonGroup1.add(unico);
        unico.setText("Única");
        unico.setContentAreaFilled(false);
        unico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unicoActionPerformed(evt);
            }
        });
        jPanel1.add(unico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        buttonGroup1.add(multiple);
        multiple.setText("Múltiple");
        multiple.setContentAreaFilled(false);
        multiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleActionPerformed(evt);
            }
        });
        jPanel1.add(multiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        buttonGroup2.add(r2);
        r2.setText("2");
        r2.setContentAreaFilled(false);
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        buttonGroup2.add(r3);
        r3.setText("3");
        r3.setContentAreaFilled(false);
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        buttonGroup1.add(abierto);
        abierto.setText("Abierto");
        abierto.setContentAreaFilled(false);
        abierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abiertoActionPerformed(evt);
            }
        });
        jPanel1.add(abierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 90, -1));

        actual.setEditable(false);
        actual.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 90, -1));
        jPanel1.add(R4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 120, -1));
        jPanel1.add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 120, -1));
        jPanel1.add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 120, -1));
        jPanel1.add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 120, -1));
        jPanel1.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 120, -1));
        jPanel1.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 120, -1));
        jPanel1.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 120, -1));
        jPanel1.add(puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, -1));

        QPR.setText("?");
        QPR.setBorder(null);
        QPR.setContentAreaFilled(false);
        QPR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QPRActionPerformed(evt);
            }
        });
        jPanel1.add(QPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 20, -1));

        QPD.setText("?");
        QPD.setBorder(null);
        QPD.setContentAreaFilled(false);
        QPD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QPDActionPerformed(evt);
            }
        });
        jPanel1.add(QPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unicoActionPerformed
        CtrlPreguntas.unico(unico, r2, r3, r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, D1, D2, D3);
    }//GEN-LAST:event_unicoActionPerformed

    private void multipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleActionPerformed
        CtrlPreguntas.multiple(multiple, r2, r3, r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, D1, D2, D3);
    }//GEN-LAST:event_multipleActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        CtrlPreguntas.r2(r2, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, D1, D2, D3);
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        CtrlPreguntas.r3(r3, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, D1, D2, D3);
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        CtrlPreguntas.r4(r4, false, true, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, D1, D2, D3);
    }//GEN-LAST:event_r4ActionPerformed

    private void abiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abiertoActionPerformed
        if (abierto.isSelected() == true) {
            CtrlPreguntas.inicio(r2, r3, r4, false, txtR1, txtR2, txtR3, txtR4, R1, R2, R3, R4, txtD1, txtD2, txtD3, D1, D2, D3);
        }
    }//GEN-LAST:event_abiertoActionPerformed

    private void QPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QPRActionPerformed
        JOptionPane.showMessageDialog(null, "Valores positivos (sin signo).");
    }//GEN-LAST:event_QPRActionPerformed

    private void QPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QPDActionPerformed
        JOptionPane.showMessageDialog(null, "Valores negaritos (sin signo).");
    }//GEN-LAST:event_QPDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField D1;
    public javax.swing.JTextField D2;
    public javax.swing.JTextField D3;
    public javax.swing.JButton QPD;
    public javax.swing.JButton QPR;
    public javax.swing.JTextField R1;
    public javax.swing.JTextField R2;
    public javax.swing.JTextField R3;
    public javax.swing.JTextField R4;
    public javax.swing.JCheckBox abierto;
    public javax.swing.JTextField actual;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnTodos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JCheckBox multiple;
    public javax.swing.JTextField puntos;
    public javax.swing.JCheckBox r2;
    public javax.swing.JCheckBox r3;
    public javax.swing.JCheckBox r4;
    public javax.swing.JTextField txtD1;
    public javax.swing.JTextField txtD2;
    public javax.swing.JTextField txtD3;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextPane txtPreguntas;
    public javax.swing.JTextField txtR1;
    public javax.swing.JTextField txtR2;
    public javax.swing.JTextField txtR3;
    public javax.swing.JTextField txtR4;
    public javax.swing.JCheckBox unico;
    // End of variables declaration//GEN-END:variables
}
